### ISSUE TITLE
messaging: empty state for when one tries to tag someone that is not in a chat room

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#2968] opened 2023-02-24 05:06 UTC
Instead of showing this empty box, the box should probably just disappear.

<img width="348" alt="Screen Shot 2023-02-23 at 11 06 01 PM" src="https://user-images.githubusercontent.com/6990215/221096679-b409d5ad-ebca-40ec-8090-9b687dd464cd.png">

**Comment by trucy** [comment] 2023-02-24 15:39
getting some weird tag results for other queries too. some return a single username (as expected), and sometimes double

<img width="203" alt="Screenshot 2023-02-24 at 9 38 09 AM" src="https://user-images.githubusercontent.com/321395/221220683-5950c473-880f-4b47-894d-64cc165cff66.png">
<img width="202" alt="Screenshot 2023-02-24 at 9 38 02 AM" src="https://user-images.githubusercontent.com/321395/221220687-6a0b45fd-9f68-4e24-bb4c-f2e7565951c4.png">
<img width="206" alt="Screenshot 2023-02-24 at 9 37 38 AM" src="https://user-images.githubusercontent.com/321395/221220689-e9f433e4-6e7f-4184-969f-c20657605a70.png">

**Comment by armaniferrante** [comment] 2023-03-02 02:02
not really a dup?

**Comment by armaniferrante** [comment] 2023-03-02 02:03
Note: this issue is because tristan is not actually in this chat. Adding new title.

**Comment by trucy** [comment] 2023-03-02 19:07
> Not really a dup? One issue is for no users able to be tagged and another is fur duplicates.

ah sorry, what i meant was my comment was a dupe of a ticket that already exists

**Closed** 2023-03-02 19:15 UTC
Labels: priority 1
