### ISSUE TITLE
Group chat info drawer sometimes gets stuck in loading empty state

### ISSUE THREAD

**Issue by aarongillett** [coral-xyz/backpack#3078] opened 2023-03-01 20:13 UTC
Drawer gets stuck in this stretched loading state. I can sometimes reproduce it if I close the drawer, go back and quickly open the page and drawer again.
<img width="487" alt="Screenshot 2023-03-01 at 21 06 16" src="https://user-images.githubusercontent.com/4157473/222254042-92d5c293-0d04-4b4a-8f1e-d29a649fa8c9.png">

**Comment by armaniferrante** [comment] 2023-03-02 00:35
as part of this we should also cleanup some of these skeletons

**Comment by callensm** [comment] 2023-03-02 00:52
the PR i just merged fixes the stretched skeletons at the top, but could not reproduce the loading state being stuck.

**Comment by armaniferrante** [comment] 2023-03-02 01:37
Going to close. Please re-open if this is still reproducible on the latest build.

**Closed by armaniferrante** 2023-03-02 01:37 UTC
Labels: bug, priority 1
