### ISSUE TITLE
provide ability to create a wallet with a ledger

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/backpack#830] opened 2022-09-22 20:35 UTC
right now the keyring assumes the existence of a mnemonic

**Comment by Arrowana** [comment] 2022-09-27 03:23
This is one of the most horrid UX aspect of most wallets out there.

**Comment by tomlinton** [comment] 2022-09-28 02:24
Related https://github.com/coral-xyz/backpack/issues/678

**Comment by tomlinton** [comment] 2022-10-14 06:13
Closing as duplicate of https://github.com/coral-xyz/backpack/issues/994

**Closed by tomlinton** 2022-10-14 06:13 UTC
