### ISSUE TITLE
Unable to interact with Magic Eden 'Bidding Wallet' 

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1429] opened 2022-11-05 12:20 UTC
if you deposit into ME's 'bidding wallet', unable to re-signin to trading wallet withdraw or trade those funds. Also, sometimes not able to deposit to trading wallet. 

![imagefail](https://user-images.githubusercontent.com/63250024/200119352-3a0542a4-c364-4f34-9b32-b4648f1b6209.png)
https://user-images.githubusercontent.com/63250024/200119329-90eefc51-e4bd-46eb-ab60-9da77e3f5101.mp4
<img width="822" alt="Screen Shot 2022-11-05 at 12 16 51 PM" src="https://user-images.githubusercontent.com/63250024/200119594-2e23ef74-2789-4808-bc42-b36744108559.png">

**Comment by nickFNY** [comment] 2022-11-05 12:25
![imageanother](https://user-images.githubusercontent.com/63250024/200119756-737caa71-2698-4013-9d2b-5734418dd426.png)

**Comment by tomlinton** [comment] 2022-11-11 20:40
Can't reproduce on `master` so assuming it'll be fixed in the next Chrome release.

**Comment by tomlinton** [comment] 2022-11-15 00:00
New Chrome release is available so assuming this is fixed.

**Closed by tomlinton** 2022-11-15 00:00 UTC
Labels: beta-feedback
