### ISSUE TITLE
Wallet imported from phantom seed phrase would not show correct balances or NFTs

### ISSUE THREAD

**Issue by nickFNY** [coral-xyz/backpack#1444] opened 2022-11-08 23:39 UTC
A user imported a seed phrase from phantom, when selecting which address to import the accurate SOL balance appeared in the preview. After selecting and importing, the wallet showed 0 balance and 0 NFTs. After several days, the user re-installed backpack and tried again to the same result.

**Comment by skynetcap** [comment] 2022-11-11 08:19
I'd suspect this is related to the multiple possible derivation paths for mnemonic. Optimally, Backpack searches account across derived across all paths, to guess which path is correct.

**Comment by tomlinton** [comment] 2022-11-11 20:34
> I'd suspect this is related to the multiple possible derivation paths for mnemonic. Optimally, Backpack would search account across derived across all paths, chooses the path with the most aggregate SOL balance, to guess which path is correct. The other paths should be shown in the UI too if not.

This is how it works for the import account flow.

As to what the issue is here - not sure. Could you ask them to screenshot the balances at both points? Where it is correct and where it is not? I suspect they may be confusing addresses.

**Comment by tomlinton** [comment] 2022-11-14 23:59
They may have also confused blockchains. Closing this for now as I don't think it is a bug - but please reopen if further information arises.

**Closed by tomlinton** 2022-11-14 23:59 UTC
Labels: beta-feedback
